name: AnyRouter 自动签到
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: windows-latest
    environment: production
    env:
      PYTHONIOENCODING: utf-8
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装 uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 缓存 uv 依赖
    - name: 缓存 uv 依赖
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\uv\cache
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: 安装依赖
      run: |
        uv sync

    - name: 缓存 Playwright 浏览器
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~\AppData\Local\ms-playwright
        key: playwright-chromium-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          playwright-chromium-

    - name: 安装 Playwright 浏览器
      run: |
        uv run playwright install chromium --with-deps

    - name: 验证 Playwright 安装
      run: |
        uv run python -c "from playwright.sync_api import sync_playwright; print('Playwright 可用')"

    - name: 执行签到
      env:
        ANYROUTER_ACCOUNTS: ${{ secrets.ANYROUTER_ACCOUNTS }}
        DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
        FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
        WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
      run: |
        uv run checkin.py

    - name: 显示执行结果
      if: always()
      run: |
        echo "签到任务执行完成"
        echo "时间: $(Get-Date)"
